// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {oauth} from '../models';

export function SignIn():Promise<oauth.UserInfo>;

export function SignOut():Promise<void>;
